### ISSUE TITLE
geo apply fails on Terraform 0.9+

### ISSUE THREAD

**Issue by anthonyagresta** [coinbase/geoengineer#122]
When using a version of the `terraform` binary 0.9 or newer, after confirming the plan,`geo apply` fails to invoke terraform with the following error message:

```
Failed to load backend: State path cannot be specified with a plan file. The plan itself contains
the state to use. If you wish to change that, please create a new plan
and specify the state path when creating the plan.
```

The same plan applies cleanly when I replace my terraform binary with v0.8.8.

It looks like 0.9 added a breaking change in the terraform command line behavior, causing it to fail to run with both a state file and a plan specified, e.g.:

`terraform apply -parallelism=12 -state=terraform.tfstate plan.terraform`

Same results on both linux and OSX.

**Comment by grahamjenson** [comment]
Hey,

This issue was fixed a while back, but not published to ruby gems. I just released a new version of GeoEngineer (0.1.4) that should fix this. Internally we are using terraform 9.5 so should work with this version.

Thanks for creating the issue.
