### ISSUE TITLE
QUESTION:  Why no support for terraform destroy?

### ISSUE THREAD

**Issue by jrm16020** [coinbase/geoengineer#127]
I'll start by saying I'm really excited by what I see so far with Geo.  That said I'm curious if there's a reason why you've not provided support for `geo destroy`.  Would you be open to pull requests that add the functionality?

**Comment by grahamjenson** [comment]
We are always open to pull requests 😄   The main hurdle will be that by default we attach a life cycle state to not destroy any resources, this is for safety to make sure we only explicitly destroy resources. Given `geo destroy` would be an explicit command it would be a great addition.

**Comment by jrm16020** [comment]
Understood @grahamjenson.  Thank you for the feedback!  I think I've got it working already and should be able to open a PR soon.

**Comment by jrm16020** [comment]
I'll leave this issue open and open the PR against it.

**Comment by grahamjenson** [comment]
Cheers, this was a great addition.
