### ISSUE TITLE
QUESTION: When will be the next release?

### ISSUE THREAD

**Issue by Chehai** [coinbase/geoengineer#154]
Thanks for this great work! We are wondering when the next version will be released. We would like to get recent bug fixes.

**Comment by grahamjenson** [comment]
Sorry for the delay. Internally we are using the commit sha to update Geo so have been a bit slack on releasing versions. Will get to this soon.

**Comment by Chehai** [comment]
Thank you! Let me close the issue.

**Comment by grahamjenson** [comment]
@Chehai Just published geoengineer 0.1.5

**Comment by Chehai** [comment]
Great! Thank you!
