### ISSUE TITLE
Question about Terraform

### ISSUE THREAD

**Issue by pkleanthous** [coinbase/geoengineer#179]
Hi guys,

May I ask why are you using Terraform under the hood instead of aws Ruby SDK for the same operations?

**Comment by grahamjenson** [comment]
Terraform provides us a lot of useful abstraction from the AWS SDK. The most useful part is the collection and comparison of the existing state in AWS and the wanted state that is defined in the DSL. AWS has a brooad set of APIs to collect and manage the resources it provides, by us using terraform we only have to be concerned with the interaction with terraform and not each individual AWS resource.
