### ISSUE TITLE
Unreviewed commit on master!

### ISSUE THREAD

**Issue by heimdall-asguard** [coinbase/geoengineer#180]
Unreviewed commit(s) [COMPARE](https://github.com/coinbase/geoengineer/compare/474e9afc3cef1e900dd4f5f2784c8a8c0a13d777...76ded6cd665c9ddd5a7139e3e5b96e5f7fdf20fe) was merged to master by sds.

Comment with appropriate number of :+1: to approve.

**Comment by grahamjenson** [comment]
+1

**Comment by heimdall-asguard** [comment]
Reviews      | 1/1 | Message
------------ | ------------- | ----------
grahamjenson | 1 | +1 



[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/geoengineer&ref=94f0a96070db66947b53337bd26d1903e882f18e)

**Comment by heimdall-asguard** [comment]
Review Error for sds@2018-01-30T01:50:03+00:00
User cannot review their own pull request

**Comment by krobertson** [comment]
+1

**Comment by heimdall-asguard** [comment]
Reviews      | 2/1 | Message
------------ | ------------- | ----------
grahamjenson | 1 | +1 
krobertson | 1 | +1 



[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/geoengineer&ref=94f0a96070db66947b53337bd26d1903e882f18e)

**Comment by chwevans** [comment]
👍

**Comment by heimdall-asguard** [comment]
Review Error for chwevans@2018-01-30T21:10:14+00:00
User failed mfa authentication

**Comment by chwevans** [comment]
👍

**Comment by samnrubin** [comment]
👍

**Comment by heimdall-asguard** [comment]
Reviews      | 3/1 | Message
------------ | ------------- | ----------
grahamjenson | 1 | +1 
krobertson | 1 | +1 
samnrubin | 1 | 👍  



[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/geoengineer&ref=94f0a96070db66947b53337bd26d1903e882f18e)

**Comment by lian** [comment]
+1

**Comment by heimdall-asguard** [comment]
Reviews      | 4/1 | Message
------------ | ------------- | ----------
grahamjenson | 1 | +1 
krobertson | 1 | +1 
samnrubin | 1 | 👍  
lian | 1 | +1 



[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/geoengineer&ref=94f0a96070db66947b53337bd26d1903e882f18e)

**Comment by chwevans** [comment]
👍

**Comment by lukedemi** [comment]
+1

**Comment by heimdall-asguard** [comment]
Review Error for lukedemi@2018-01-30T21:38:29+00:00
User failed mfa authentication
