### ISSUE TITLE
`--quiet` flag doesn't work

### ISSUE THREAD

**Issue by Korede-TA** [coinbase/geoengineer#189]
Adding the `--quiet` flag when calling the executable `./geo` doesn't seem to do anything to the output.

Gemfile Ref Version: [1ae4d29](https://github.com/coinbase/geoengineer/commit/1ae4d29a5138cf9672505b8ccfeec7c861d41505)

**Comment by itstehkman** [comment]
@Korede-TA the quiet flag sets the verbose variable here: https://github.com/coinbase/geoengineer/blob/1ae4d29a5138cf9672505b8ccfeec7c861d41505/lib/geoengineer/cli/geo_cli.rb#L174

and the verbose variable affects how some things are printed to stdout, namely the shell_exec function, which is used for terraform apply and plan steps.

could you provide a specific example of what you expected and what you actually got?

**Comment by sds** [comment]
We are no longer supporting this repository. Closing this issue and archiving.
