### ISSUE TITLE
SQS name property marked as required

### ISSUE THREAD

**Issue by thomasklinger1234** [coinbase/geoengineer#203]
Hello, 

I am trying to create a SQS queue with the following code 

```
project.resource("aws_sqs_queue", "test_queue") {
  name_prefix "test_queue"
  delay_seconds 90
  max_message_size 2048
  message_retention_seconds 86400
  receive_wait_time_seconds 0
  tags {
    environment "staging"
  }
  kms_master_key_id "alias/aws/sqs"
  kms_data_key_reuse_period_seconds 900
}
``` 

In the [terraform documentation](https://www.terraform.io/docs/providers/aws/r/sqs_queue.html) the `name` property is marked as optional, however in geoengineer it is marked as required (see [here](https://github.com/coinbase/geoengineer/blob/master/lib/geoengineer/resources/aws_sqs_queue.rb)).

```
> geo apply -e staging main.rb
Using environment 'staging'
unable to load 'environments/staging'
ERROR: name attribute nil for aws_sqs_queue.test_queue
ERROR: name attribute nil for aws_sqs_queue.test_queue
Total Errors 2
```

**Comment by sds** [comment]
We are no longer supporting this repository. Closing this issue and archiving.
