### ISSUE TITLE
validate_has_tag ensures tag on all tags subresource instead of one that exists

### ISSUE THREAD

**Issue by grahamjenson** [coinbase/geoengineer#30]
e.g. 

```
resource() {
  tags {
     Name 'asd'
 }
 tags {}
}
```

will fail if validate_has_tag(:Name) because it ensures all tags subresources have Name, not just one.

**Comment by grahamjenson** [comment]
test

**Comment by grahamjenson** [comment]
retest

**Comment by itstehkman** [comment]
@grahamjenson do you still want this fixed? seems easy

**Comment by grahamjenson** [comment]
yup, though it might be fixed. should check first.

**Comment by sds** [comment]
We are no longer supporting this repository. Closing this issue and archiving.
